#!/usr/bin/env python3
"""Translate HomeFaq.tsx and other specific files with long content."""
import os

ROOT = "/workspaces/Marinara-Engine/packages/client/src"

FAQ_TRANSLATIONS = [
    # QUICK_FIXES
    ("Raise max response length if agents, trackers, or Lorebook Keeper keep failing or returning broken JSON.",
     "Aumente o comprimento máximo de resposta se agentes, rastreadores ou o Guardião de Lore continuarem falhando ou retornando JSON inválido."),
    ("Update before digging too deep. If you installed from Git, use the updater or the Advanced settings update check.",
     "Atualize antes de investigar muito fundo. Se instalou pelo Git, use o atualizador ou a verificação em Configurações Avançadas."),
    ("If the installer or startup scripts vanished, check antivirus quarantine first and whitelist the Marinara folder.",
     "Se o instalador ou scripts de inicialização sumiram, verifique a quarentena do antivírus e adicione a pasta Marinara às exceções."),
    ("If Game Mode setup keeps failing, switch to a stronger model before changing prompts or presets.",
     "Se a configuração do Modo Jogo continua falhando, mude para um modelo mais forte antes de alterar prompts ou predefinições."),
    # Categories
    ('"Top Issue"', '"Problema Principal"'),
    ('"Setup"', '"Configuração"'),
    ('"Connections"', '"Conexões"'),
    ('"Core"', '"Essencial"'),
    ('"Agents"', '"Agentes"'),
    ('"Images"', '"Imagens"'),
    ('"Game Mode"', '"Modo Jogo"'),
    ('"Misc"', '"Outros"'),
    # Category styles keys
    ('"Top Issue":', '"Problema Principal":'),
    ('"Game Mode":', '"Modo Jogo":'),
    # Questions
    ('question: "What model should I use for Game Mode?"',
     'question: "Qual modelo devo usar no Modo Jogo?"'),
    ('question: "My trackers, Lorebook Keeper, or agents do nothing or fail with a max length error. What fixes that?"',
     'question: "Meus rastreadores, Guardião de Lore ou agentes não fazem nada ou falham com erro de comprimento máximo. O que resolve?"'),
    ('question: "I saw \'[sidecar] Startup with max GPU offload failed, retrying with CPU fallback\'. Is that normal?"',
     'question: "Vi \'[sidecar] Startup with max GPU offload failed, retrying with CPU fallback\'. Isso é normal?"'),
    ('question: "My antivirus flagged the installer or deleted files. Is Marinara safe?"',
     'question: "Meu antivírus sinalizou o instalador ou excluiu arquivos. O Marinara é seguro?"'),
    ('question: "I get a blank page or ERR_EMPTY_RESPONSE on localhost:7860. What should I try?"',
     'question: "Recebo uma página em branco ou ERR_EMPTY_RESPONSE em localhost:7860. O que devo tentar?"'),
    ('question: "How do I update without the installer?"',
     'question: "Como atualizo sem o instalador?"'),
    ('question: "Is the Android APK standalone?"',
     'question: "O APK Android é independente?"'),
    ('question: "\'pnpm: not found\' or install.bat failed. What now?"',
     'question: "\'pnpm: not found\' ou install.bat falhou. E agora?"'),
    ('question: "Can I use Google Cloud\'s free credit with Marinara?"',
     'question: "Posso usar o crédito gratuito do Google Cloud com o Marinara?"'),
    ('question: "What is the best local model right now?"',
     'question: "Qual é o melhor modelo local agora?"'),
    ('question: "How do I use a bigger model for agents instead of the local sidecar?"',
     'question: "Como uso um modelo maior para agentes em vez do sidecar local?"'),
    ('question: "How do I use Claude Code or a reverse proxy?"',
     'question: "Como uso o Claude Code ou um proxy reverso?"'),
    ('question: "NanoGPT is throwing 401 errors. Why does recreating the connection help?"',
     'question: "O NanoGPT está retornando erros 401. Por que recriar a conexão ajuda?"'),
    ('question: "Where do I change temperature, top-p, and other sampler settings?"',
     'question: "Onde altero temperatura, top-p e outras configurações de amostragem?"'),
    ('question: "How do I enable agents?"',
     'question: "Como ativo os agentes?"'),
    ('question: "Where is the list of supported macros?"',
     'question: "Onde está a lista de macros suportadas?"'),
    ('question: "How do I switch between different chats with the same character?"',
     'question: "Como alterno entre conversas diferentes com o mesmo personagem?"'),
    ('question: "Where are my chats, presets, and other data stored?"',
     'question: "Onde ficam minhas conversas, predefinições e outros dados?"'),
    ('question: "How do I hide a message from the prompt without deleting it?"',
     'question: "Como oculto uma mensagem do prompt sem excluí-la?"'),
    ('question: "How does SillyTavern import behave?"',
     'question: "Como funciona a importação do SillyTavern?"'),
    ('question: "Prose Guardian is impersonating me or writing the whole reply. Is that normal?"',
     'question: "O Guardião de Prosa está me imitando ou escrevendo a resposta inteira. Isso é normal?"'),
    ('question: "What counts as high or low for attribute stats?"',
     'question: "O que conta como alto ou baixo para atributos?"'),
    ('question: "Narrative Director is capturing my messages and bot replies inside itself. Why?"',
     'question: "O Diretor Narrativo está capturando minhas mensagens e respostas do bot dentro de si. Por quê?"'),
    ('question: "How do I get ComfyUI or Illustrator working?"',
     'question: "Como faço o ComfyUI ou o Ilustrador funcionar?"'),
    ('question: "How do I change image resolution?"',
     'question: "Como altero a resolução da imagem?"'),
    ('question: "I got a \'Temp must be 1\' error while using Illustrate. Which temperature is wrong?"',
     'question: "Recebi um erro \'Temp must be 1\' ao usar o Ilustrador. Qual temperatura está errada?"'),
    ('question: "How do I get booru-style prompts from Illustrator?"',
     'question: "Como obtenho prompts no estilo booru do Ilustrador?"'),
    ('question: "How do I generate character sprites?"',
     'question: "Como gero sprites de personagens?"'),
    ('question: "Game Mode first generation failed with invalid JSON. How do I stabilize it?"',
     'question: "A primeira geração do Modo Jogo falhou com JSON inválido. Como estabilizo?"'),
    ('question: "Can I edit widgets, scenes, or journal-like Game Mode data after the fact?"',
     'question: "Posso editar widgets, cenas ou dados do Modo Jogo depois?"'),
    ('question: "Can I add new party members mid-game?"',
     'question: "Posso adicionar novos membros ao grupo durante o jogo?"'),
    ('question: "How do I change the Game Mode background?"',
     'question: "Como altero o plano de fundo do Modo Jogo?"'),
    ('question: "Can I talk to the GM directly instead of playing in-character?"',
     'question: "Posso falar diretamente com o Mestre em vez de jogar no personagem?"'),
    ('question: "Does ending a session summarize it and let me continue later?"',
     'question: "Encerrar uma sessão a resume e permite continuar depois?"'),
    ('question: "Is there built-in content filtering?"',
     'question: "Há filtragem de conteúdo integrada?"'),
    ('question: "Can I run RP and image generation on the same GPU?"',
     'question: "Posso rodar RP e geração de imagens na mesma GPU?"'),
    ('question: "Is there a mobile app?"',
     'question: "Há um aplicativo móvel?"'),
    ('question: "Does Marinara support TTS?"',
     'question: "O Marinara suporta TTS?"'),
    ('question: "Can I chat in languages other than English? What about the UI?"',
     'question: "Posso conversar em outros idiomas além do inglês? E a interface?"'),
    ('question: "Where should I report bugs or request features?"',
     'question: "Onde devo reportar bugs ou solicitar funcionalidades?"'),
    # Answers
    ('answer: "Game Mode is much pickier than regular chat, especially during first generation and session setup."',
     'answer: "O Modo Jogo é muito mais exigente que o chat normal, especialmente na primeira geração e configuração de sessão."'),
    ('answer:\n      "The most common fix is increasing max response length so the model can finish the tracker JSON instead of truncating it."',
     'answer:\n      "A correção mais comum é aumentar o comprimento máximo de resposta para o modelo terminar o JSON do rastreador sem truncar."'),
    ('answer:\n      "Usually yes. Marinara\'s local sidecar is meant to live on CPU and RAM so your main RP model can keep the GPU and VRAM."',
     'answer:\n      "Geralmente sim. O sidecar local do Marinara é projetado para rodar em CPU e RAM para que seu modelo principal mantenha a GPU e VRAM."'),
    ('answer: "This is a very common false-positive path for installers and batch files that spawn local services."',
     'answer: "Este é um caminho muito comum de falso positivo para instaladores e arquivos batch que iniciam serviços locais."'),
    ('answer: "This is usually a browser state problem rather than a dead install."',
     'answer: "Geralmente é um problema de estado do navegador, não uma instalação corrompida."'),
    ('answer: "The updater expects a real Git checkout."',
     'answer: "O atualizador espera um checkout Git real."'),
    ('answer: "No. The APK is only a WebView shell for Marinara Engine running locally in Termux."',
     'answer: "Não. O APK é apenas um shell WebView para o Marinara Engine rodando localmente no Termux."'),
    ('answer: "Your system usually just does not have pnpm available yet."',
     'answer: "Seu sistema geralmente ainda não tem o pnpm disponível."'),
    ('answer: "Usually yes, but not every Google route behaves the same."',
     'answer: "Geralmente sim, mas nem todo caminho do Google se comporta igual."'),
    ('answer: "Gemma 4 is still the safest recommendation for most local users."',
     'answer: "Gemma 4 ainda é a recomendação mais segura para a maioria dos usuários locais."'),
    ('answer:\n      "Create a normal connection to your own Kobold, llama.cpp, or compatible endpoint and mark it for agent use."',
     'answer:\n      "Crie uma conexão normal para seu próprio Kobold, llama.cpp ou endpoint compatível e marque-a para uso por agentes."'),
    ('answer: "There is no separate reverse-proxy field like SillyTavern uses."',
     'answer: "Não há campo separado de proxy reverso como o SillyTavern usa."'),
    ('answer: "That has been one of the more reliable fixes for NanoGPT-specific auth weirdness."',
     'answer: "Essa tem sido uma das correções mais confiáveis para problemas de autenticação específicos do NanoGPT."'),
    ('answer: "Open a chat, then use the right panel\'s Advanced Settings."',
     'answer: "Abra uma conversa e use as Configurações Avançadas no painel direito."'),
    ('answer: "The answer depends on the mode."',
     'answer: "A resposta depende do modo."'),
    ('answer: "Type /macros directly in chat."',
     'answer: "Digite /macros diretamente no chat."'),
    ('answer: "Use Recent Chats from the home screen or the branch-aware chat browser inside the app."',
     'answer: "Use Conversas Recentes na tela inicial ou o navegador de conversas dentro do app."'),
    ('answer: "The main local database lives in packages/server/data/marinara-engine.db."',
     'answer: "O banco de dados local principal fica em packages/server/data/marinara-engine.db."'),
    ('answer: "Open the message actions and use the eyeball icon."',
     'answer: "Abra as ações da mensagem e use o ícone de olho."'),
    ('answer: "Most data imports cleanly, but there are a few recurring gotchas."',
     'answer: "A maioria dos dados importa corretamente, mas há alguns problemas recorrentes."'),
    ('answer: "No. That is usually a weak agent-model problem, not what the agent is supposed to do."',
     'answer: "Não. Geralmente é um problema de modelo de agente fraco, não o comportamento esperado."'),
    ('answer:\n      "The default expectation is basically DnD-style 1 to 20, but the model still interprets the fiction around it."',
     'answer:\n      "A expectativa padrão é basicamente estilo DnD de 1 a 20, mas o modelo ainda interpreta a ficção ao redor."'),
    ('answer: "That has shown up most often with weaker or unstable model choices, especially GLM 5.1 style runs."',
     'answer: "Isso aparece com mais frequência com modelos mais fracos ou instáveis, especialmente rodadas no estilo GLM 5.1."'),
    ('answer: "The workflow template has to expose the placeholders Marinara expects."',
     'answer: "O template de workflow deve expor os placeholders que o Marinara espera."'),
    ('answer: "Set it on the image-generation connection itself."',
     'answer: "Defina na própria conexão de geração de imagens."'),
    ('answer: "Usually the image connection, not your main chat model."',
     'answer: "Geralmente a conexão de imagem, não seu modelo principal de chat."'),
    ('answer: "Edit the Illustrator agent prompt in the Agents section."',
     'answer: "Edite o prompt do agente Ilustrador na seção de Agentes."'),
    ('answer: "Open the character card and use the sprite generation flow from there."',
     'answer: "Abra a ficha do personagem e use o fluxo de geração de sprites a partir daí."'),
    ('answer: "Start by upgrading the model before changing anything else."',
     'answer: "Comece atualizando o modelo antes de mudar qualquer outra coisa."'),
    ('answer: "Some of that is editable now, but not every auto-tracked piece is equally exposed yet."',
     'answer: "Parte disso é editável agora, mas nem tudo que é rastreado automaticamente está igualmente exposto."'),
    ('answer: "Yes. Marinara can recruit party members during an active game now."',
     'answer: "Sim. O Marinara pode recrutar membros do grupo durante um jogo ativo agora."'),
    ('answer: "The quickest path is usually to talk to the GM directly or rerun the scene or image pass for that beat."',
     'answer: "O caminho mais rápido geralmente é falar diretamente com o Mestre ou reexecutar a cena ou passagem de imagem."'),
    ('answer: "Yes. Switch into GM chat mode when you need direct out-of-scene help."',
     'answer: "Sim. Mude para o modo de chat com o Mestre quando precisar de ajuda direta fora da cena."'),
    ('answer: "Yes. Ending a session generates continuity data and the next session can resume from that state later."',
     'answer: "Sim. Encerrar uma sessão gera dados de continuidade e a próxima sessão pode retomar desse estado."'),
    ('answer:\n      "Not as a separate Marinara safety layer. Filtering behavior mostly depends on the model or provider you connect."',
     'answer:\n      "Não como uma camada de segurança separada do Marinara. O comportamento de filtragem depende principalmente do modelo ou provedor conectado."'),
    ('answer: "Sometimes, but VRAM is the hard limit."',
     'answer: "Às vezes, mas a VRAM é o limite rígido."'),
    ('answer:\n      "Not as a standalone app yet. You can install Marinara as a PWA from the browser on phones and tablets while the server runs on your computer, Docker host, or Termux device."',
     'answer:\n      "Ainda não como app independente. Você pode instalar o Marinara como PWA pelo navegador em celulares e tablets enquanto o servidor roda no seu computador, host Docker ou dispositivo Termux."'),
    ('answer: "Yes. There is built-in support for OpenAI-compatible TTS providers now."',
     'answer: "Sim. Há suporte integrado para provedores TTS compatíveis com OpenAI agora."'),
    ('answer: "Chat content works in other languages, but the UI itself is still English-first."',
     'answer: "O conteúdo do chat funciona em outros idiomas, mas a interface ainda é prioritariamente em inglês."'),
    ('answer: "Use the dedicated bug and feedback channel in Discord rather than dropping reports into general chat."',
     'answer: "Use o canal dedicado de bugs e feedback no Discord em vez de postar relatórios no chat geral."'),
    # UI labels in HomeFaq
    ('"Quick Fixes"', '"Correções Rápidas"'),
    ('"Frequently Asked Questions"', '"Perguntas Frequentes"'),
    ('"FAQ"', '"FAQ"'),
    (">Quick Fixes<", ">Correções Rápidas<"),
    (">Frequently Asked Questions<", ">Perguntas Frequentes<"),
    (">Show all<", ">Mostrar tudo<"),
    (">Show less<", ">Mostrar menos<"),
    (">Show more<", ">Mostrar mais<"),
    (">Show all questions<", ">Mostrar todas as perguntas<"),
    (">Collapse<", ">Recolher<"),
    (">Expand<", ">Expandir<"),
    # Category style keys (must match translated category names)
    ('"Top Issue": "border-rose', '"Problema Principal": "border-rose'),
    ('"Game Mode": "border-orange', '"Modo Jogo": "border-orange'),
]

def translate_file(path, translations):
    with open(path, "r", encoding="utf-8") as f:
        content = f.read()
    original = content
    for eng, pt in translations:
        content = content.replace(eng, pt)
    if content != original:
        with open(path, "w", encoding="utf-8") as f:
            f.write(content)
        return True
    return False

faq_path = os.path.join(ROOT, "components/chat/HomeFaq.tsx")
if translate_file(faq_path, FAQ_TRANSLATIONS):
    print(f"  translated: components/chat/HomeFaq.tsx")
else:
    print("  no changes: components/chat/HomeFaq.tsx")

print("Done.")
