#!/usr/bin/env python3
"""Translate UI strings in all client .tsx/.ts files from English to Brazilian Portuguese."""
import os, re, sys

ROOT = "/workspaces/Marinara-Engine/packages/client/src"

# (exact_string, replacement) — order matters, longer strings first
TRANSLATIONS = [
    # ── Modes ──
    ("A straightforward AI conversation — no roleplay elements.", "Uma conversa direta com IA — sem elementos de roleplay."),
    ("Immersive roleplay with characters, game state tracking, and world simulation.", "Roleplay imersivo com personagens, rastreamento de estado e simulação de mundo."),
    ("A full game experience with backgrounds, sprites, text boxes, and choices.", "Experiência completa de jogo com cenários, sprites, caixas de texto e escolhas."),
    ("AI-managed singleplayer RPG with a Game Master, party, dice, maps, and quests.", "RPG solo gerenciado por IA com Mestre, grupo, dados, mapas e missões."),
    # ── Sidebar modes ──
    ('"Conversation"', '"Conversa"'),
    ('"Roleplay"', '"Roleplay"'),
    ('"Visual Novel"', '"Romance Visual"'),
    ('"Game"', '"Jogo"'),
    ("label: \"Conversation\"", "label: \"Conversa\""),
    ("label: \"Roleplay\"", "label: \"Roleplay\""),
    ("label: \"Visual Novel\"", "label: \"Romance Visual\""),
    ("label: \"Game\"", "label: \"Jogo\""),
    ("shortLabel: \"CONVO\"", "shortLabel: \"CONV\""),
    ("shortLabel: \"RP\"", "shortLabel: \"RP\""),
    ("shortLabel: \"VN\"", "shortLabel: \"RV\""),
    ("shortLabel: \"GM\"", "shortLabel: \"JOGO\""),
    # ── Sidebar UI ──
    ("title=\"Delete Folder\"", "title=\"Excluir Pasta\""),
    ("title: \"Delete Folder\"", "title: \"Excluir Pasta\""),
    ("message: \"Delete this folder? Chats will be moved to the top level.\"", "message: \"Excluir esta pasta? As conversas serão movidas para o nível superior.\""),
    ("confirmLabel: \"Delete\"", "confirmLabel: \"Excluir\""),
    ("title: \"Delete Chats\"", "title: \"Excluir Conversas\""),
    ("title: \"Delete Chat\"", "title: \"Excluir Conversa\""),
    ("message: \"Delete this chat?\"", "message: \"Excluir esta conversa?\""),
    ("title: \"Unsaved Changes\"", "title: \"Alterações Não Salvas\""),
    ("message: \"You have unsaved changes. Discard and continue?\"", "message: \"Você tem alterações não salvas. Descartar e continuar?\""),
    ("confirmLabel: \"Discard\"", "confirmLabel: \"Descartar\""),
    ("Export failed", "Falha na exportação"),
    ("title=\"Move to folder\"", "title=\"Mover para pasta\""),
    ("title=\"Close\"", "title=\"Fechar\""),
    ("title=\"Sort chats\"", "title=\"Ordenar conversas\""),
    ("title=\"Collapse tags\"", "title=\"Recolher tags\""),
    ("title=\"Expand tags\"", "title=\"Expandir tags\""),
    ("\"Checking...\"", "\"Verificando...\""),
    ("\"Try Again\"", "\"Tentar Novamente\""),
    ("placeholder=\"Folder name...\"", "placeholder=\"Nome da pasta...\""),
    ("\"Cancel\"", "\"Cancelar\""),
    ("\"Select\"", "\"Selecionar\""),
    ("title=\"Delete Chat\"", "title=\"Excluir Conversa\""),
    ("title=\"Move to Folder\"", "title=\"Mover para Pasta\""),
    ("title=\"Rename folder\"", "title=\"Renomear pasta\""),
    ("title=\"Change activity status\"", "title=\"Alterar status de atividade\""),
    ("aria-label=\"Change activity status\"", "aria-label=\"Alterar status de atividade\""),
    ("placeholder=\"What are you doing?\"", "placeholder=\"O que você está fazendo?\""),
    ("aria-label=\"Custom activity\"", "aria-label=\"Atividade personalizada\""),
    ("label: \"Active\"", "label: \"Ativo\""),
    ("description: \"You're online and available\"", "description: \"Você está online e disponível\""),
    ("label: \"Idle\"", "label: \"Ausente\""),
    ("description: \"Automatic when you're away\"", "description: \"Automático quando você está ausente\""),
    ("label: \"Do Not Disturb\"", "label: \"Não Perturbe\""),
    ("description: \"Suppress auto messages\"", "description: \"Suprimir mensagens automáticas\""),
    ("\"Collapse tags\"", "\"Recolher tags\""),
    ("\"Expand tags\"", "\"Expandir tags\""),
    ("\"New Conversation\"", "\"Nova Conversa\""),
    ("\"New Roleplay\"", "\"Novo Roleplay\""),
    ("\"New Game\"", "\"Novo Jogo\""),
    ("+ New Conversation", "+ Nova Conversa"),
    ("+ New Roleplay", "+ Novo Roleplay"),
    ("+ New Game", "+ Novo Jogo"),
    # ── Common UI ──
    (">Loading...<", ">Carregando...<"),
    ("\"Loading...\"", "\"Carregando...\""),
    (">Save<", ">Salvar<"),
    (">Cancel<", ">Cancelar<"),
    (">Delete<", ">Excluir<"),
    (">Close<", ">Fechar<"),
    (">Edit<", ">Editar<"),
    (">Create<", ">Criar<"),
    (">Import<", ">Importar<"),
    (">Export<", ">Exportar<"),
    (">Search<", ">Buscar<"),
    (">Settings<", ">Configurações<"),
    (">Back<", ">Voltar<"),
    (">Next<", ">Próximo<"),
    (">Done<", ">Concluído<"),
    (">Confirm<", ">Confirmar<"),
    (">Add<", ">Adicionar<"),
    (">Remove<", ">Remover<"),
    (">Reset<", ">Redefinir<"),
    (">Apply<", ">Aplicar<"),
    (">Copy<", ">Copiar<"),
    (">Paste<", ">Colar<"),
    (">Duplicate<", ">Duplicar<"),
    (">Rename<", ">Renomear<"),
    (">Download<", ">Baixar<"),
    (">Upload<", ">Enviar<"),
    (">Generate<", ">Gerar<"),
    (">Regenerate<", ">Regenerar<"),
    (">Retry<", ">Tentar Novamente<"),
    (">Continue<", ">Continuar<"),
    (">Stop<", ">Parar<"),
    (">Send<", ">Enviar<"),
    (">New<", ">Novo<"),
    (">Open<", ">Abrir<"),
    (">View<", ">Ver<"),
    (">Enable<", ">Ativar<"),
    (">Disable<", ">Desativar<"),
    (">Enabled<", ">Ativado<"),
    (">Disabled<", ">Desativado<"),
    (">Yes<", ">Sim<"),
    (">No<", ">Não<"),
    (">OK<", ">OK<"),
    (">Error<", ">Erro<"),
    (">Warning<", ">Aviso<"),
    (">Success<", ">Sucesso<"),
    (">Loading<", ">Carregando<"),
    (">Saving<", ">Salvando<"),
    (">Saved<", ">Salvo<"),
    (">Deleting<", ">Excluindo<"),
    (">Deleted<", ">Excluído<"),
    # ── Placeholders ──
    ("placeholder=\"Search...\"", "placeholder=\"Buscar...\""),
    ("placeholder=\"Search\"", "placeholder=\"Buscar\""),
    ("placeholder=\"Name...\"", "placeholder=\"Nome...\""),
    ("placeholder=\"Name\"", "placeholder=\"Nome\""),
    ("placeholder=\"Description...\"", "placeholder=\"Descrição...\""),
    ("placeholder=\"Enter name...\"", "placeholder=\"Digite o nome...\""),
    ("placeholder=\"Enter a name...\"", "placeholder=\"Digite um nome...\""),
    ("placeholder=\"Type a message...\"", "placeholder=\"Digite uma mensagem...\""),
    ("placeholder=\"Type here...\"", "placeholder=\"Digite aqui...\""),
    ("placeholder=\"Add a tag...\"", "placeholder=\"Adicionar tag...\""),
    ("placeholder=\"No description\"", "placeholder=\"Sem descrição\""),
    # ── Titles / Labels ──
    ("title=\"Search\"", "title=\"Buscar\""),
    ("title=\"Settings\"", "title=\"Configurações\""),
    ("title=\"Delete\"", "title=\"Excluir\""),
    ("title=\"Edit\"", "title=\"Editar\""),
    ("title=\"Save\"", "title=\"Salvar\""),
    ("title=\"Close\"", "title=\"Fechar\""),
    ("title=\"Add\"", "title=\"Adicionar\""),
    ("title=\"Remove\"", "title=\"Remover\""),
    ("title=\"Copy\"", "title=\"Copiar\""),
    ("title=\"Duplicate\"", "title=\"Duplicar\""),
    ("title=\"Rename\"", "title=\"Renomear\""),
    ("title=\"Download\"", "title=\"Baixar\""),
    ("title=\"Export\"", "title=\"Exportar\""),
    ("title=\"Import\"", "title=\"Importar\""),
    ("title=\"Generate\"", "title=\"Gerar\""),
    ("title=\"Regenerate\"", "title=\"Regenerar\""),
    ("title=\"Retry\"", "title=\"Tentar Novamente\""),
    ("title=\"Cancel\"", "title=\"Cancelar\""),
    ("title=\"Confirm\"", "title=\"Confirmar\""),
    ("title=\"Back\"", "title=\"Voltar\""),
    ("title=\"Next\"", "title=\"Próximo\""),
    ("title=\"Done\"", "title=\"Concluído\""),
    ("title=\"Reset\"", "title=\"Redefinir\""),
    ("title=\"Apply\"", "title=\"Aplicar\""),
    ("title=\"Enable\"", "title=\"Ativar\""),
    ("title=\"Disable\"", "title=\"Desativar\""),
    ("title=\"New chat\"", "title=\"Nova conversa\""),
    ("title=\"New Chat\"", "title=\"Nova Conversa\""),
    ("title=\"Create\"", "title=\"Criar\""),
    ("title=\"Open\"", "title=\"Abrir\""),
    ("title=\"View\"", "title=\"Ver\""),
    ("title=\"Pin\"", "title=\"Fixar\""),
    ("title=\"Unpin\"", "title=\"Desafixar\""),
    ("title=\"Expand\"", "title=\"Expandir\""),
    ("title=\"Collapse\"", "title=\"Recolher\""),
    ("title=\"Refresh\"", "title=\"Atualizar\""),
    ("title=\"Reload\"", "title=\"Recarregar\""),
    ("title=\"Upload\"", "title=\"Enviar\""),
    ("title=\"Send\"", "title=\"Enviar\""),
    ("title=\"Stop\"", "title=\"Parar\""),
    ("title=\"Continue\"", "title=\"Continuar\""),
    ("title=\"Toggle\"", "title=\"Alternar\""),
    ("title=\"More options\"", "title=\"Mais opções\""),
    ("title=\"More\"", "title=\"Mais\""),
    ("title=\"Less\"", "title=\"Menos\""),
    ("title=\"Show\"", "title=\"Mostrar\""),
    ("title=\"Hide\"", "title=\"Ocultar\""),
    ("title=\"Move up\"", "title=\"Mover para cima\""),
    ("title=\"Move down\"", "title=\"Mover para baixo\""),
    ("title=\"Drag to reorder\"", "title=\"Arrastar para reordenar\""),
    ("title=\"Copy to clipboard\"", "title=\"Copiar para área de transferência\""),
    ("title=\"Copied!\"", "title=\"Copiado!\""),
    # ── Panels ──
    (">Characters<", ">Personagens<"),
    (">Lorebooks<", ">Livros de Lore<"),
    (">Presets<", ">Predefinições<"),
    (">Connections<", ">Conexões<"),
    (">Agents<", ">Agentes<"),
    (">Personas<", ">Personas<"),
    (">Settings<", ">Configurações<"),
    (">Inventory<", ">Inventário<"),
    # ── Characters panel ──
    (">No characters yet<", ">Nenhum personagem ainda<"),
    (">No characters found<", ">Nenhum personagem encontrado<"),
    (">Create Character<", ">Criar Personagem<"),
    (">Import Character<", ">Importar Personagem<"),
    (">Create with AI<", ">Criar com IA<"),
    (">Browse Characters<", ">Explorar Personagens<"),
    (">Set as default<", ">Definir como padrão<"),
    (">Default<", ">Padrão<"),
    # ── Lorebooks panel ──
    (">No lorebooks yet<", ">Nenhum livro de lore ainda<"),
    (">Create Lorebook<", ">Criar Livro de Lore<"),
    (">Import Lorebook<", ">Importar Livro de Lore<"),
    (">Create with AI<", ">Criar com IA<"),
    # ── Presets panel ──
    (">No presets yet<", ">Nenhuma predefinição ainda<"),
    (">Create Preset<", ">Criar Predefinição<"),
    (">Import Preset<", ">Importar Predefinição<"),
    # ── Connections panel ──
    (">No connections yet<", ">Nenhuma conexão ainda<"),
    (">Create Connection<", ">Criar Conexão<"),
    (">Test<", ">Testar<"),
    (">Testing...<", ">Testando...<"),
    (">Connected<", ">Conectado<"),
    (">Disconnected<", ">Desconectado<"),
    # ── Agents panel ──
    (">No agents yet<", ">Nenhum agente ainda<"),
    (">Create Agent<", ">Criar Agente<"),
    (">Built-in<", ">Integrado<"),
    (">Custom<", ">Personalizado<"),
    (">Active<", ">Ativo<"),
    (">Inactive<", ">Inativo<"),
    # ── Personas panel ──
    (">No personas yet<", ">Nenhuma persona ainda<"),
    (">Create Persona<", ">Criar Persona<"),
    (">Import Persona<", ">Importar Persona<"),
    # ── Settings panel ──
    (">General<", ">Geral<"),
    (">Appearance<", ">Aparência<"),
    (">Advanced<", ">Avançado<"),
    (">About<", ">Sobre<"),
    (">Theme<", ">Tema<"),
    (">Dark<", ">Escuro<"),
    (">Light<", ">Claro<"),
    (">System<", ">Sistema<"),
    (">Language<", ">Idioma<"),
    (">Font Size<", ">Tamanho da Fonte<"),
    (">Font<", ">Fonte<"),
    (">Notifications<", ">Notificações<"),
    (">Sound<", ">Som<"),
    (">Auto-scroll<", ">Rolagem automática<"),
    (">Streaming<", ">Streaming<"),
    (">Debug<", ">Depuração<"),
    (">Version<", ">Versão<"),
    (">Update<", ">Atualizar<"),
    (">Check for updates<", ">Verificar atualizações<"),
    (">Backup<", ">Backup<"),
    (">Restore<", ">Restaurar<"),
    # ── Chat UI ──
    (">New Conversation<", ">Nova Conversa<"),
    (">New Roleplay<", ">Novo Roleplay<"),
    (">New Game<", ">Novo Jogo<"),
    (">No chats yet<", ">Nenhuma conversa ainda<"),
    (">No messages yet<", ">Nenhuma mensagem ainda<"),
    (">Start a conversation<", ">Iniciar uma conversa<"),
    (">Type a message<", ">Digite uma mensagem<"),
    (">Generating...<", ">Gerando...<"),
    (">Thinking...<", ">Pensando...<"),
    (">Regenerate<", ">Regenerar<"),
    (">Edit message<", ">Editar mensagem<"),
    (">Delete message<", ">Excluir mensagem<"),
    (">Copy message<", ">Copiar mensagem<"),
    (">Swipe left<", ">Deslizar esquerda<"),
    (">Swipe right<", ">Deslizar direita<"),
    (">Branch<", ">Ramificação<"),
    (">Branches<", ">Ramificações<"),
    (">Translate<", ">Traduzir<"),
    (">Original<", ">Original<"),
    (">Translated<", ">Traduzido<"),
    (">Attach file<", ">Anexar arquivo<"),
    (">Attach image<", ">Anexar imagem<"),
    (">Voice input<", ">Entrada de voz<"),
    (">Emoji<", ">Emoji<"),
    (">GIF<", ">GIF<"),
    (">Chat settings<", ">Configurações da conversa<"),
    (">Chat Settings<", ">Configurações da Conversa<"),
    # ── Game UI ──
    (">Game Master<", ">Mestre do Jogo<"),
    (">Party<", ">Grupo<"),
    (">Quest<", ">Missão<"),
    (">Quests<", ">Missões<"),
    (">Journal<", ">Diário<"),
    (">Map<", ">Mapa<"),
    (">Combat<", ">Combate<"),
    (">Encounter<", ">Encontro<"),
    (">Roll dice<", ">Rolar dados<"),
    (">Skill check<", ">Teste de habilidade<"),
    (">Game setup<", ">Configuração do jogo<"),
    (">Game Setup<", ">Configuração do Jogo<"),
    (">Start game<", ">Iniciar jogo<"),
    (">Start Game<", ">Iniciar Jogo<"),
    (">End session<", ">Encerrar sessão<"),
    (">End Session<", ">Encerrar Sessão<"),
    (">Session summary<", ">Resumo da sessão<"),
    (">Session Summary<", ">Resumo da Sessão<"),
    (">Save checkpoint<", ">Salvar ponto de controle<"),
    (">Save Checkpoint<", ">Salvar Ponto de Controle<"),
    (">Restore checkpoint<", ">Restaurar ponto de controle<"),
    (">Restore Checkpoint<", ">Restaurar Ponto de Controle<"),
    (">Checkpoints<", ">Pontos de Controle<"),
    (">Inventory<", ">Inventário<"),
    (">Equipment<", ">Equipamento<"),
    (">Stats<", ">Atributos<"),
    (">Skills<", ">Habilidades<"),
    (">Level<", ">Nível<"),
    (">Experience<", ">Experiência<"),
    (">Health<", ">Vida<"),
    (">Mana<", ">Mana<"),
    (">Stamina<", ">Stamina<"),
    (">Gold<", ">Ouro<"),
    (">Attack<", ">Ataque<"),
    (">Defense<", ">Defesa<"),
    (">Speed<", ">Velocidade<"),
    (">Strength<", ">Força<"),
    (">Dexterity<", ">Destreza<"),
    (">Intelligence<", ">Inteligência<"),
    (">Wisdom<", ">Sabedoria<"),
    (">Charisma<", ">Carisma<"),
    (">Constitution<", ">Constituição<"),
    (">Luck<", ">Sorte<"),
    # ── Modals ──
    (">Create Character<", ">Criar Personagem<"),
    (">Import Character<", ">Importar Personagem<"),
    (">Create Lorebook<", ">Criar Livro de Lore<"),
    (">Import Lorebook<", ">Importar Livro de Lore<"),
    (">Create Preset<", ">Criar Predefinição<"),
    (">Import Preset<", ">Importar Predefinição<"),
    (">Create Connection<", ">Criar Conexão<"),
    (">Create Persona<", ">Criar Persona<"),
    (">Import Persona<", ">Importar Persona<"),
    (">Edit Agent<", ">Editar Agente<"),
    # ── Editors ──
    (">Character Editor<", ">Editor de Personagem<"),
    (">Lorebook Editor<", ">Editor de Livro de Lore<"),
    (">Preset Editor<", ">Editor de Predefinição<"),
    (">Connection Editor<", ">Editor de Conexão<"),
    (">Persona Editor<", ">Editor de Persona<"),
    (">Agent Editor<", ">Editor de Agente<"),
    (">Name<", ">Nome<"),
    (">Description<", ">Descrição<"),
    (">Personality<", ">Personalidade<"),
    (">Scenario<", ">Cenário<"),
    (">First message<", ">Primeira mensagem<"),
    (">First Message<", ">Primeira Mensagem<"),
    (">System prompt<", ">Prompt do sistema<"),
    (">System Prompt<", ">Prompt do Sistema<"),
    (">Tags<", ">Tags<"),
    (">Avatar<", ">Avatar<"),
    (">Background<", ">Plano de fundo<"),
    (">Voice<", ">Voz<"),
    (">Model<", ">Modelo<"),
    (">Temperature<", ">Temperatura<"),
    (">Max tokens<", ">Máximo de tokens<"),
    (">Max Tokens<", ">Máximo de Tokens<"),
    (">Context<", ">Contexto<"),
    (">Memory<", ">Memória<"),
    (">World info<", ">Informações do mundo<"),
    (">World Info<", ">Informações do Mundo<"),
    # ── Onboarding ──
    (">Welcome<", ">Bem-vindo<"),
    (">Get started<", ">Começar<"),
    (">Get Started<", ">Começar<"),
    (">Skip<", ">Pular<"),
    (">Finish<", ">Finalizar<"),
    (">Previous<", ">Anterior<"),
    # ── Specific titles found in codebase ──
    ("title=\"Remove from chat\"", "title=\"Remover da conversa\""),
    ("title=\"Remove from group\"", "title=\"Remover do grupo\""),
    ("title=\"Remove from party\"", "title=\"Remover do grupo\""),
    ("title=\"Remove from message\"", "title=\"Remover da mensagem\""),
    ("title=\"Generate NPC portrait\"", "title=\"Gerar retrato de NPC\""),
    ("title=\"Upload or replace NPC portrait\"", "title=\"Enviar ou substituir retrato de NPC\""),
    ("title=\"Regenerate the Game Lorebook Keeper entries for this latest session\"", "title=\"Regenerar entradas do Guardião de Lore para esta sessão\""),
    ("title=\"Regenerate this session conclusion\"", "title=\"Regenerar conclusão desta sessão\""),
    ("title=\"Restart voice-over\"", "title=\"Reiniciar narração\""),
    ("title=\"Stop voice-over\"", "title=\"Parar narração\""),
    ("title=\"Update game plot arcs from this session\"", "title=\"Atualizar arcos de enredo desta sessão\""),
    ("title=\"Delete file\"", "title=\"Excluir arquivo\""),
    ("title=\"Delete group\"", "title=\"Excluir grupo\""),
    ("title=\"Delete key detail\"", "title=\"Excluir detalhe chave\""),
    ("title=\"Rename group\"", "title=\"Renomear grupo\""),
    ("title=\"Start New Chat\"", "title=\"Iniciar Nova Conversa\""),
    ("title=\"Add all to chat\"", "title=\"Adicionar todos à conversa\""),
    ("title=\"Add stat\"", "title=\"Adicionar atributo\""),
    ("title=\"Clear keyword test\"", "title=\"Limpar teste de palavra-chave\""),
    ("title=\"Delete checkpoint\"", "title=\"Excluir ponto de controle\""),
    ("title=\"End Session\"", "title=\"Encerrar Sessão\""),
    ("title=\"Estimated from character card text fields; actual tokenizer counts vary by model.\"", "title=\"Estimado a partir dos campos de texto do personagem; contagens reais variam por modelo.\""),
    ("title=\"Open character card\"", "title=\"Abrir ficha do personagem\""),
    ("title=\"Remove attribute\"", "title=\"Remover atributo\""),
    ("title=\"Remove strength\"", "title=\"Remover força\""),
    ("title=\"Remove weakness\"", "title=\"Remover fraqueza\""),
    ("title=\"Volume\"", "title=\"Volume\""),
    ("title=\"Active World Info\"", "title=\"Informações do Mundo Ativas\""),
    ("title=\"Close frame editor\"", "title=\"Fechar editor de quadro\""),
    ("title=\"Mark this long-term arc as complete\"", "title=\"Marcar este arco de longo prazo como concluído\""),
    ("title=\"Mark this long-term arc as complete without deleting the arc notes.\"", "title=\"Marcar este arco como concluído sem excluir as notas.\""),
    ("title=\"Add to chat\"", "title=\"Adicionar à conversa\""),
    ("title=\"Assign personas\"", "title=\"Atribuir personas\""),
    ("title=\"Chat Settings\"", "title=\"Configurações da Conversa\""),
    ("title=\"Close logs\"", "title=\"Fechar logs\""),
    ("title=\"Disconnect\"", "title=\"Desconectar\""),
    ("title=\"Edit tags\"", "title=\"Editar tags\""),
    ("title=\"Exit combat and remove the turn that started it\"", "title=\"Sair do combate e remover o turno que o iniciou\""),
    ("title=\"Frame sprite\"", "title=\"Enquadrar sprite\""),
    ("title=\"Gallery\"", "title=\"Galeria\""),
    ("title=\"Game Assets\"", "title=\"Recursos do Jogo\""),
    ("title=\"Game Mode Tutorial\"", "title=\"Tutorial do Modo Jogo\""),
    ("title=\"History\"", "title=\"Histórico\""),
    ("title=\"Journal\"", "title=\"Diário\""),
    ("title=\"Load checkpoint\"", "title=\"Carregar ponto de controle\""),
    ("title=\"Manage Chat Files\"", "title=\"Gerenciar Arquivos da Conversa\""),
    ("title=\"Open combat logs\"", "title=\"Abrir logs de combate\""),
    ("title=\"Delete branch\"", "title=\"Excluir ramificação\""),
    ("title=\"Log out\"", "title=\"Sair\""),
    ("title=\"Open image\"", "title=\"Abrir imagem\""),
    ("title=\"Remove ability\"", "title=\"Remover habilidade\""),
    ("title=\"Remove detail\"", "title=\"Remover detalhe\""),
    ("title=\"Remove option\"", "title=\"Remover opção\""),
    ("title=\"Remove persona\"", "title=\"Remover persona\""),
    ("title=\"Remove saved status\"", "title=\"Remover status salvo\""),
    ("title=\"Remove character voice\"", "title=\"Remover voz do personagem\""),
    ("title=\"Remove character\"", "title=\"Remover personagem\""),
    ("title=\"Rename branch\"", "title=\"Renomear ramificação\""),
    ("title=\"Restart speaking\"", "title=\"Reiniciar fala\""),
    ("title=\"Strengths\"", "title=\"Pontos Fortes\""),
    ("title=\"Weaknesses\"", "title=\"Pontos Fracos\""),
    ("title=\"Set as active\"", "title=\"Definir como ativo\""),
    ("title=\"Start Combat Encounter\"", "title=\"Iniciar Encontro de Combate\""),
    ("title=\"View fullscreen\"", "title=\"Ver em tela cheia\""),
    ("title=\"Pin to chat\"", "title=\"Fixar na conversa\""),
    ("title=\"Pin image to chat\"", "title=\"Fixar imagem na conversa\""),
    ("title=\"Game actions\"", "title=\"Ações do jogo\""),
    ("title=\"Increase amount\"", "title=\"Aumentar quantidade\""),
    ("title=\"Load older logs\"", "title=\"Carregar logs anteriores\""),
    ("title=\"Load the entire session log\"", "title=\"Carregar todo o log da sessão\""),
    ("title=\"Paint original pixels back in\"", "title=\"Restaurar pixels originais\""),
    ("title=\"Paint with the selected color\"", "title=\"Pintar com a cor selecionada\""),
    ("title=\"Pick brush color from the sprite\"", "title=\"Selecionar cor do sprite\""),
    ("title=\"How closely pixels must match the sampled cleanup color\"", "title=\"Quão próximos os pixels devem ser da cor de limpeza\""),
    ("title=\"How strongly the brush avoids character-like edge pixels\"", "title=\"Quão fortemente o pincel evita pixels de borda\""),
    ("title=\"Soften the edge of the cleaned brush stroke\"", "title=\"Suavizar a borda do traço limpo\""),
    ("title=\"Approximate tokens in the current session's loaded chat history.\"", "title=\"Tokens aproximados no histórico carregado da sessão atual.\""),
    ("title=\"Click to rename\"", "title=\"Clique para renomear\""),
    ("title=\"Copy current prompt to a new template\"", "title=\"Copiar prompt atual para novo template\""),
    ("title=\"Expand editor\"", "title=\"Expandir editor\""),
    ("title=\"Expand value editor\"", "title=\"Expandir editor de valor\""),
    ("title=\"Edit sheet\"", "title=\"Editar ficha\""),
    ("title=\"Regenerate sheet\"", "title=\"Regenerar ficha\""),
    ("title=\"Re-run full secret plot state\"", "title=\"Reexecutar estado completo do enredo secreto\""),
    ("title=\"Re-run scene directions\"", "title=\"Reexecutar direções de cena\""),
    ("title=\"Delete gallery image\"", "title=\"Excluir imagem da galeria\""),
    ("title=\"Retry...\"", "title=\"Tentar novamente...\""),
    ("title=\"Retry\"", "title=\"Tentar novamente\""),
    ("title=\"View image fullscreen\"", "title=\"Ver imagem em tela cheia\""),
    ("title=\"Brush color\"", "title=\"Cor do pincel\""),
    # ── aria-labels ──
    ("aria-label=\"Active World Info\"", "aria-label=\"Informações do Mundo Ativas\""),
    ("aria-label=\"Close frame editor\"", "aria-label=\"Fechar editor de quadro\""),
    ("aria-label=\"Decrease trigger cadence\"", "aria-label=\"Diminuir cadência de disparo\""),
    ("aria-label=\"Increase trigger cadence\"", "aria-label=\"Aumentar cadência de disparo\""),
    ("aria-label=\"Mark this long-term arc as complete\"", "aria-label=\"Marcar arco de longo prazo como concluído\""),
    ("aria-label=\"Clear keyword test\"", "aria-label=\"Limpar teste de palavra-chave\""),
    ("aria-label=\"Retry\"", "aria-label=\"Tentar novamente\""),
    ("aria-label=\"Retry...\"", "aria-label=\"Tentar novamente...\""),
    ("aria-label=\"Remove image from message\"", "aria-label=\"Remover imagem da mensagem\""),
    ("aria-label=\"Summary prompt template\"", "aria-label=\"Template de prompt de resumo\""),
    ("aria-label=\"Copy current prompt to a new template\"", "aria-label=\"Copiar prompt atual para novo template\""),
    ("aria-label=\"Pin image to chat\"", "aria-label=\"Fixar imagem na conversa\""),
    ("aria-label=\"View image fullscreen\"", "aria-label=\"Ver imagem em tela cheia\""),
    ("aria-label=\"Brush color\"", "aria-label=\"Cor do pincel\""),
    ("aria-label=\"Delete gallery image\"", "aria-label=\"Excluir imagem da galeria\""),
    ("aria-label=\"Edit sheet\"", "aria-label=\"Editar ficha\""),
    ("aria-label=\"Regenerate sheet\"", "aria-label=\"Regenerar ficha\""),
    ("aria-label=\"Re-run full secret plot state\"", "aria-label=\"Reexecutar estado do enredo secreto\""),
    ("aria-label=\"Re-run scene directions\"", "aria-label=\"Reexecutar direções de cena\""),
    # ── Placeholders específicos ──
    ("placeholder=\"Activity description\"", "placeholder=\"Descrição da atividade\""),
    ("placeholder=\"How the next session should resume\"", "placeholder=\"Como a próxima sessão deve retomar\""),
    ("placeholder=\"One continuity fact per line, including discoveries, twists, and reveals\"", "placeholder=\"Um fato de continuidade por linha, incluindo descobertas e reviravoltas\""),
    ("placeholder=\"One moment per line\"", "placeholder=\"Um momento por linha\""),
    ("placeholder=\"One small preference, habit, promise, or past detail per line\"", "placeholder=\"Uma preferência, hábito, promessa ou detalhe por linha\""),
    ("placeholder=\"One update per line\"", "placeholder=\"Uma atualização por linha\""),
    ("placeholder=\"One plot twist per line\"", "placeholder=\"Uma reviravolta por linha\""),
    ("placeholder=\"Impulsive, poor swimmer, etc.\"", "placeholder=\"Impulsivo, mau nadador, etc.\""),
    ("placeholder=\"Prompt instructions for manual summary generation...\"", "placeholder=\"Instruções de prompt para geração manual de resumo...\""),
    ("placeholder=\"Reliable, quick thinker, etc.\"", "placeholder=\"Confiável, pensador rápido, etc.\""),
    ("placeholder=\"STR\"", "placeholder=\"FOR\""),
    ("placeholder=\"Speaker name\"", "placeholder=\"Nome do falante\""),
    ("placeholder=\"Template name\"", "placeholder=\"Nome do template\""),
    ("placeholder=\"Dual-wielding, Arcane shield, etc.\"", "placeholder=\"Dual-wielding, Escudo arcano, etc.\""),
    ("placeholder=\"Lockpicking, survival, marksmanship\"", "placeholder=\"Abrir fechaduras, sobrevivência, pontaria\""),
    ("placeholder=\"Skills\"", "placeholder=\"Habilidades\""),
    ("placeholder=\"Search characters…\"", "placeholder=\"Buscar personagens…\""),
    ("placeholder=\"Search entries…\"", "placeholder=\"Buscar entradas…\""),
    ("placeholder=\"Search functions…\"", "placeholder=\"Buscar funções…\""),
    ("placeholder=\"Stat name\"", "placeholder=\"Nome do atributo\""),
    ("placeholder=\"Value…\"", "placeholder=\"Valor…\""),
    ("placeholder=\"Label…\"", "placeholder=\"Rótulo…\""),
    ("placeholder=\"Label (e.g. Combat Skills)\"", "placeholder=\"Rótulo (ex: Habilidades de Combate)\""),
    ("placeholder=\"Brief character summary\"", "placeholder=\"Resumo breve do personagem\""),
    ("placeholder=\"Class or role\"", "placeholder=\"Classe ou função\""),
    ("placeholder=\"Description of this parameter…\"", "placeholder=\"Descrição deste parâmetro…\""),
    ("placeholder=\"Replace individual character scenarios with a shared scenario for this group chat or leave empty to keep them…\"", "placeholder=\"Substitua os cenários individuais por um cenário compartilhado ou deixe vazio para mantê-los…\""),
    ("placeholder=\"Add tag…\"", "placeholder=\"Adicionar tag…\""),
    ("placeholder=\"Custom model ID…\"", "placeholder=\"ID do modelo personalizado…\""),
    ("placeholder=\"Direction...\"", "placeholder=\"Direção...\""),
    ("placeholder=\"Paste a paragraph or sample messages here…\"", "placeholder=\"Cole um parágrafo ou mensagens de exemplo aqui…\""),
    ("placeholder=\"Default\"", "placeholder=\"Padrão\""),
    ("placeholder=\"Field name\"", "placeholder=\"Nome do campo\""),
    ("placeholder=\"Field\"", "placeholder=\"Campo\""),
    ("placeholder=\"Item name\"", "placeholder=\"Nome do item\""),
    ("placeholder=\"Name\"", "placeholder=\"Nome\""),
    ("placeholder=\"Paste your Spotify app Client ID...\"", "placeholder=\"Cole o Client ID do seu app Spotify...\""),
    # ── confirmLabels ──
    ("confirmLabel: \"Conclude\"", "confirmLabel: \"Concluir\""),
    ("confirmLabel: \"Enable anyway\"", "confirmLabel: \"Ativar mesmo assim\""),
    ("confirmLabel: \"End Combat\"", "confirmLabel: \"Encerrar Combate\""),
    # ── messages ──
    ("message: \"Conclude this encounter early?\"", "message: \"Concluir este encontro antecipadamente?\""),
    ("message: \"Close and end this combat?\"", "message: \"Fechar e encerrar este combate?\""),
    ("message: \"Delete this chat?\"", "message: \"Excluir esta conversa?\""),
    # ── labels ──
    ("label: \"Misc Agents\"", "label: \"Agentes Diversos\""),
    ("label: \"Tracker Agents\"", "label: \"Agentes de Rastreamento\""),
    ("label: \"Writer Agents\"", "label: \"Agentes de Escrita\""),
    # ── Misc ──
    (">No results<", ">Sem resultados<"),
    (">No results found<", ">Nenhum resultado encontrado<"),
    (">Something went wrong<", ">Algo deu errado<"),
    (">Try again<", ">Tentar novamente<"),
    (">Refresh<", ">Atualizar<"),
    (">Copied!<", ">Copiado!<"),
    (">Copied to clipboard<", ">Copiado para área de transferência<"),
    (">Unsaved changes<", ">Alterações não salvas<"),
    (">Unsaved Changes<", ">Alterações Não Salvas<"),
    (">Are you sure?<", ">Tem certeza?<"),
    (">This action cannot be undone.<", ">Esta ação não pode ser desfeita.<"),
    (">Optional<", ">Opcional<"),
    (">Required<", ">Obrigatório<"),
    (">Default<", ">Padrão<"),
    (">Custom<", ">Personalizado<"),
    (">None<", ">Nenhum<"),
    (">All<", ">Todos<"),
    (">Unknown<", ">Desconhecido<"),
    (">Online<", ">Online<"),
    (">Offline<", ">Offline<"),
    (">Connected<", ">Conectado<"),
    (">Disconnected<", ">Desconectado<"),
    (">Enabled<", ">Ativado<"),
    (">Disabled<", ">Desativado<"),
    (">On<", ">Ligado<"),
    (">Off<", ">Desligado<"),
    (">New<", ">Novo<"),
    (">Beta<", ">Beta<"),
    (">Pro<", ">Pro<"),
    (">Free<", ">Grátis<"),
    (">Premium<", ">Premium<"),
]

def translate_file(path):
    with open(path, "r", encoding="utf-8") as f:
        content = f.read()
    original = content
    for eng, pt in TRANSLATIONS:
        content = content.replace(eng, pt)
    if content != original:
        with open(path, "w", encoding="utf-8") as f:
            f.write(content)
        return True
    return False

changed = 0
for dirpath, dirnames, filenames in os.walk(ROOT):
    dirnames[:] = [d for d in dirnames if d != "node_modules"]
    for fname in filenames:
        if fname.endswith(".tsx") or fname.endswith(".ts"):
            path = os.path.join(dirpath, fname)
            if translate_file(path):
                changed += 1
                print(f"  translated: {path[len(ROOT)+1:]}")

print(f"\nDone. {changed} files modified.")
