#!/usr/bin/env python3
"""Second pass: translate JSX text content, toast messages, and error strings."""
import os

ROOT = "/workspaces/Marinara-Engine/packages/client/src"

TRANSLATIONS = [
    # ── Empty states ──
    ("No lorebooks match your search", "Nenhum livro de lore corresponde à busca"),
    ("No lorebooks yet", "Nenhum livro de lore ainda"),
    ("No characters found.", "Nenhum personagem encontrado."),
    ("No characters found. Create characters first.", "Nenhum personagem encontrado. Crie personagens primeiro."),
    ("No personas found. Create one in the Personas panel.", "Nenhuma persona encontrada. Crie uma no painel de Personas."),
    ("No matches.", "Nenhuma correspondência."),
    ("No connections available", "Nenhuma conexão disponível"),
    ("No personas created yet.", "Nenhuma persona criada ainda."),
    ("No characters selected", "Nenhum personagem selecionado"),
    ("No personas selected", "Nenhuma persona selecionada"),
    ("No characters available.", "Nenhum personagem disponível."),
    ("No character tags available.", "Nenhuma tag de personagem disponível."),
    ("No trigger filters available.", "Nenhum filtro de gatilho disponível."),
    ("No sources available.", "Nenhuma fonte disponível."),
    ("No saved prompt-section output yet.", "Nenhuma saída de seção de prompt salva ainda."),
    ("No messages yet", "Nenhuma mensagem ainda"),
    ("No display color set", "Nenhuma cor de exibição definida"),
    ("No accent color set", "Nenhuma cor de destaque definida"),
    ("No surface color — neutral card", "Sem cor de superfície — cartão neutro"),
    ("No color set — uses default", "Sem cor definida — usa padrão"),
    ("No custom widgets will be used for the starting session.", "Nenhum widget personalizado será usado na sessão inicial."),
    ("No custom widgets will be carried into the next session.", "Nenhum widget personalizado será levado para a próxima sessão."),
    ("This folder is empty.", "Esta pasta está vazia."),
    ("Empty output", "Saída vazia"),
    # ── Toast / error messages ──
    ("Failed to rescan game assets.", "Falha ao reescanear recursos do jogo."),
    ("Failed to download font", "Falha ao baixar fonte"),
    ("Failed to save theme. Check the browser console for details.", "Falha ao salvar tema. Verifique o console do navegador."),
    ("Failed to reset the active theme.", "Falha ao redefinir o tema ativo."),
    ("Failed to activate theme.", "Falha ao ativar tema."),
    ("Failed to remove theme.", "Falha ao remover tema."),
    ("Failed to export profile", "Falha ao exportar perfil"),
    ("Failed to refresh the app", "Falha ao atualizar o aplicativo"),
    ("Failed to create backup", "Falha ao criar backup"),
    ("Failed to clear all data.", "Falha ao limpar todos os dados."),
    ("Failed to clear selected data.", "Falha ao limpar dados selecionados."),
    ("Failed to remove tag from some lorebooks", "Falha ao remover tag de alguns livros de lore"),
    ("Failed to export lorebooks", "Falha ao exportar livros de lore"),
    ("Failed to upload lorebook picture", "Falha ao enviar imagem do livro de lore"),
    ("Failed to connect to server", "Falha ao conectar ao servidor"),
    ("Failed to parse file", "Falha ao processar arquivo"),
    ("Failed to load character", "Falha ao carregar personagem"),
    ("Failed to load character details", "Falha ao carregar detalhes do personagem"),
    ("Failed to download character card", "Falha ao baixar ficha do personagem"),
    ("Failed to save lorebook", "Falha ao salvar livro de lore"),
    ("Failed to create lorebook", "Falha ao criar livro de lore"),
    ("Failed to apply character updates", "Falha ao aplicar atualizações do personagem"),
    ("Failed to save description", "Falha ao salvar descrição"),
    ("Failed to upload", "Falha ao enviar"),
    ("Could not check for updates. Try again later.", "Não foi possível verificar atualizações. Tente novamente mais tarde."),
    ("Template must not be empty.", "O template não pode estar vazio."),
    ("Unknown error", "Erro desconhecido"),
    # ── Confirm dialogs ──
    ("Are you sure you want to delete", "Tem certeza que deseja excluir"),
    # ── Settings help texts (visible) ──
    ("In Conversation and Roleplay modes, press Up Arrow while the chat input is empty to open the most recent message",
     "Nos modos Conversa e Roleplay, pressione Seta para Cima com o campo vazio para abrir a mensagem mais recente"),
    # ── Game setup ──
    ("No characters found", "Nenhum personagem encontrado"),
    # ── ChatSidebar mode labels ──
    ('"Conversation"', '"Conversa"'),
    ('"Roleplay"', '"Roleplay"'),
    ('"Game"', '"Jogo"'),
    # ── Inline JSX text nodes (wrapped in tags) ──
    (">Conversation<", ">Conversa<"),
    (">Roleplay<", ">Roleplay<"),
    (">Game<", ">Jogo<"),
    (">Visual Novel<", ">Romance Visual<"),
    (">Characters<", ">Personagens<"),
    (">Lorebooks<", ">Livros de Lore<"),
    (">Presets<", ">Predefinições<"),
    (">Connections<", ">Conexões<"),
    (">Agents<", ">Agentes<"),
    (">Settings<", ">Configurações<"),
    (">Inventory<", ">Inventário<"),
    (">Browser<", ">Navegador<"),
    (">Personas<", ">Personas<"),
    (">New Chat<", ">Nova Conversa<"),
    (">New Conversation<", ">Nova Conversa<"),
    (">New Roleplay<", ">Novo Roleplay<"),
    (">New Game<", ">Novo Jogo<"),
    (">Search<", ">Buscar<"),
    (">Save<", ">Salvar<"),
    (">Cancel<", ">Cancelar<"),
    (">Delete<", ">Excluir<"),
    (">Close<", ">Fechar<"),
    (">Edit<", ">Editar<"),
    (">Create<", ">Criar<"),
    (">Import<", ">Importar<"),
    (">Export<", ">Exportar<"),
    (">Back<", ">Voltar<"),
    (">Next<", ">Próximo<"),
    (">Done<", ">Concluído<"),
    (">Confirm<", ">Confirmar<"),
    (">Add<", ">Adicionar<"),
    (">Remove<", ">Remover<"),
    (">Reset<", ">Redefinir<"),
    (">Apply<", ">Aplicar<"),
    (">Copy<", ">Copiar<"),
    (">Duplicate<", ">Duplicar<"),
    (">Rename<", ">Renomear<"),
    (">Download<", ">Baixar<"),
    (">Upload<", ">Enviar<"),
    (">Generate<", ">Gerar<"),
    (">Regenerate<", ">Regenerar<"),
    (">Retry<", ">Tentar Novamente<"),
    (">Continue<", ">Continuar<"),
    (">Stop<", ">Parar<"),
    (">Send<", ">Enviar<"),
    (">Open<", ">Abrir<"),
    (">View<", ">Ver<"),
    (">Enable<", ">Ativar<"),
    (">Disable<", ">Desativar<"),
    (">Enabled<", ">Ativado<"),
    (">Disabled<", ">Desativado<"),
    (">Yes<", ">Sim<"),
    (">No<", ">Não<"),
    (">Loading...<", ">Carregando...<"),
    (">Saving...<", ">Salvando...<"),
    (">Generating...<", ">Gerando...<"),
    (">Thinking...<", ">Pensando...<"),
    (">Testing...<", ">Testando...<"),
    (">Checking...<", ">Verificando...<"),
    (">Deleting...<", ">Excluindo...<"),
    (">Uploading...<", ">Enviando...<"),
    (">Downloading...<", ">Baixando...<"),
    (">Connecting...<", ">Conectando...<"),
    (">Processing...<", ">Processando...<"),
    (">Refreshing...<", ">Atualizando...<"),
    (">Copied!<", ">Copiado!<"),
    (">Saved!<", ">Salvo!<"),
    (">Deleted!<", ">Excluído!<"),
    (">Error<", ">Erro<"),
    (">Warning<", ">Aviso<"),
    (">Success<", ">Sucesso<"),
    (">No results found<", ">Nenhum resultado encontrado<"),
    (">No results<", ">Sem resultados<"),
    (">Something went wrong<", ">Algo deu errado<"),
    (">Try again<", ">Tentar novamente<"),
    (">Refresh<", ">Atualizar<"),
    (">Optional<", ">Opcional<"),
    (">Required<", ">Obrigatório<"),
    (">Default<", ">Padrão<"),
    (">Custom<", ">Personalizado<"),
    (">None<", ">Nenhum<"),
    (">All<", ">Todos<"),
    (">Unknown<", ">Desconhecido<"),
    (">Online<", ">Online<"),
    (">Offline<", ">Offline<"),
    (">Connected<", ">Conectado<"),
    (">Disconnected<", ">Desconectado<"),
    (">New<", ">Novo<"),
    (">Name<", ">Nome<"),
    (">Description<", ">Descrição<"),
    (">Tags<", ">Tags<"),
    (">Avatar<", ">Avatar<"),
    (">Model<", ">Modelo<"),
    (">General<", ">Geral<"),
    (">Appearance<", ">Aparência<"),
    (">Advanced<", ">Avançado<"),
    (">About<", ">Sobre<"),
    (">Theme<", ">Tema<"),
    (">Dark<", ">Escuro<"),
    (">Light<", ">Claro<"),
    (">System<", ">Sistema<"),
    (">Language<", ">Idioma<"),
    (">Notifications<", ">Notificações<"),
    (">Sound<", ">Som<"),
    (">Debug<", ">Depuração<"),
    (">Version<", ">Versão<"),
    (">Update<", ">Atualizar<"),
    (">Backup<", ">Backup<"),
    (">Restore<", ">Restaurar<"),
    (">Welcome<", ">Bem-vindo<"),
    (">Get Started<", ">Começar<"),
    (">Skip<", ">Pular<"),
    (">Finish<", ">Finalizar<"),
    (">Previous<", ">Anterior<"),
    (">Unsaved Changes<", ">Alterações Não Salvas<"),
    (">Are you sure?<", ">Tem certeza?<"),
    (">This action cannot be undone.<", ">Esta ação não pode ser desfeita.<"),
    (">Create Character<", ">Criar Personagem<"),
    (">Import Character<", ">Importar Personagem<"),
    (">Create Lorebook<", ">Criar Livro de Lore<"),
    (">Import Lorebook<", ">Importar Livro de Lore<"),
    (">Create Preset<", ">Criar Predefinição<"),
    (">Import Preset<", ">Importar Predefinição<"),
    (">Create Connection<", ">Criar Conexão<"),
    (">Create Persona<", ">Criar Persona<"),
    (">Import Persona<", ">Importar Persona<"),
    (">Edit Agent<", ">Editar Agente<"),
    (">Create with AI<", ">Criar com IA<"),
    (">Browse Characters<", ">Explorar Personagens<"),
    (">Set as default<", ">Definir como padrão<"),
    (">Test<", ">Testar<"),
    (">Built-in<", ">Integrado<"),
    (">Active<", ">Ativo<"),
    (">Inactive<", ">Inativo<"),
    (">Party<", ">Grupo<"),
    (">Quest<", ">Missão<"),
    (">Quests<", ">Missões<"),
    (">Journal<", ">Diário<"),
    (">Map<", ">Mapa<"),
    (">Combat<", ">Combate<"),
    (">Encounter<", ">Encontro<"),
    (">Checkpoints<", ">Pontos de Controle<"),
    (">Equipment<", ">Equipamento<"),
    (">Stats<", ">Atributos<"),
    (">Skills<", ">Habilidades<"),
    (">Level<", ">Nível<"),
    (">Experience<", ">Experiência<"),
    (">Health<", ">Vida<"),
    (">Gold<", ">Ouro<"),
    (">Attack<", ">Ataque<"),
    (">Defense<", ">Defesa<"),
    (">Speed<", ">Velocidade<"),
    (">Strength<", ">Força<"),
    (">Intelligence<", ">Inteligência<"),
    (">Wisdom<", ">Sabedoria<"),
    (">Charisma<", ">Carisma<"),
    (">Constitution<", ">Constituição<"),
    (">Luck<", ">Sorte<"),
    (">Personality<", ">Personalidade<"),
    (">Scenario<", ">Cenário<"),
    (">System Prompt<", ">Prompt do Sistema<"),
    (">Memory<", ">Memória<"),
    (">World Info<", ">Informações do Mundo<"),
    (">Gallery<", ">Galeria<"),
    (">History<", ">Histórico<"),
    (">Translate<", ">Traduzir<"),
    (">Original<", ">Original<"),
    (">Translated<", ">Traduzido<"),
    (">Voice<", ">Voz<"),
    (">Temperature<", ">Temperatura<"),
    (">Context<", ">Contexto<"),
    (">Strengths<", ">Pontos Fortes<"),
    (">Weaknesses<", ">Pontos Fracos<"),
    (">Select<", ">Selecionar<"),
    (">Deselect<", ">Desselecionar<"),
    (">Select All<", ">Selecionar Todos<"),
    (">Deselect All<", ">Desselecionar Todos<"),
    (">Move<", ">Mover<"),
    (">Reorder<", ">Reordenar<"),
    (">Expand<", ">Expandir<"),
    (">Collapse<", ">Recolher<"),
    (">Pin<", ">Fixar<"),
    (">Unpin<", ">Desafixar<"),
    (">Show<", ">Mostrar<"),
    (">Hide<", ">Ocultar<"),
    (">More<", ">Mais<"),
    (">Less<", ">Menos<"),
    (">Log out<", ">Sair<"),
    (">Disconnect<", ">Desconectar<"),
    (">Connect<", ">Conectar<"),
    (">Reconnect<", ">Reconectar<"),
    (">Manage<", ">Gerenciar<"),
    (">Configure<", ">Configurar<"),
    (">Preview<", ">Visualizar<"),
    (">Test Connection<", ">Testar Conexão<"),
    (">Save Changes<", ">Salvar Alterações<"),
    (">Discard Changes<", ">Descartar Alterações<"),
    (">Unsaved changes<", ">Alterações não salvas<"),
    (">No description<", ">Sem descrição<"),
    (">No name<", ">Sem nome<"),
    (">Untitled<", ">Sem título<"),
    (">Unknown<", ">Desconhecido<"),
    (">Anonymous<", ">Anônimo<"),
    (">System<", ">Sistema<"),
    (">User<", ">Usuário<"),
    (">Assistant<", ">Assistente<"),
    (">Character<", ">Personagem<"),
    (">Persona<", ">Persona<"),
    (">Agent<", ">Agente<"),
    (">Connection<", ">Conexão<"),
    (">Preset<", ">Predefinição<"),
    (">Lorebook<", ">Livro de Lore<"),
    (">Entry<", ">Entrada<"),
    (">Entries<", ">Entradas<"),
    (">Folder<", ">Pasta<"),
    (">Folders<", ">Pastas<"),
    (">Group<", ">Grupo<"),
    (">Groups<", ">Grupos<"),
    (">Branch<", ">Ramificação<"),
    (">Branches<", ">Ramificações<"),
    (">Session<", ">Sessão<"),
    (">Sessions<", ">Sessões<"),
    (">Summary<", ">Resumo<"),
    (">Summaries<", ">Resumos<"),
    (">Checkpoint<", ">Ponto de Controle<"),
    (">Checkpoints<", ">Pontos de Controle<"),
    (">Token<", ">Token<"),
    (">Tokens<", ">Tokens<"),
    (">Message<", ">Mensagem<"),
    (">Messages<", ">Mensagens<"),
    (">Chat<", ">Conversa<"),
    (">Chats<", ">Conversas<"),
    (">Image<", ">Imagem<"),
    (">Images<", ">Imagens<"),
    (">File<", ">Arquivo<"),
    (">Files<", ">Arquivos<"),
    (">Asset<", ">Recurso<"),
    (">Assets<", ">Recursos<"),
    (">Tool<", ">Ferramenta<"),
    (">Tools<", ">Ferramentas<"),
    (">Script<", ">Script<"),
    (">Scripts<", ">Scripts<"),
    (">Template<", ">Template<"),
    (">Templates<", ">Templates<"),
    (">Prompt<", ">Prompt<"),
    (">Prompts<", ">Prompts<"),
    (">Output<", ">Saída<"),
    (">Input<", ">Entrada<"),
    (">Result<", ">Resultado<"),
    (">Results<", ">Resultados<"),
    (">Log<", ">Log<"),
    (">Logs<", ">Logs<"),
    (">Debug<", ">Depuração<"),
    (">Info<", ">Informação<"),
    (">Details<", ">Detalhes<"),
    (">Options<", ">Opções<"),
    (">Actions<", ">Ações<"),
    (">Action<", ">Ação<"),
    (">Status<", ">Status<"),
    (">Progress<", ">Progresso<"),
    (">Loading<", ">Carregando<"),
    (">Saving<", ">Salvando<"),
    (">Saved<", ">Salvo<"),
    (">Deleting<", ">Excluindo<"),
    (">Deleted<", ">Excluído<"),
    (">Created<", ">Criado<"),
    (">Updated<", ">Atualizado<"),
    (">Imported<", ">Importado<"),
    (">Exported<", ">Exportado<"),
    (">Copied<", ">Copiado<"),
    (">Pasted<", ">Colado<"),
    (">Renamed<", ">Renomeado<"),
    (">Moved<", ">Movido<"),
    (">Sorted<", ">Ordenado<"),
    (">Filtered<", ">Filtrado<"),
    (">Cleared<", ">Limpo<"),
    (">Reset<", ">Redefinido<"),
    (">Applied<", ">Aplicado<"),
    (">Enabled<", ">Ativado<"),
    (">Disabled<", ">Desativado<"),
    (">Connected<", ">Conectado<"),
    (">Disconnected<", ">Desconectado<"),
    (">Online<", ">Online<"),
    (">Offline<", ">Offline<"),
    (">Active<", ">Ativo<"),
    (">Inactive<", ">Inativo<"),
    (">Pending<", ">Pendente<"),
    (">Complete<", ">Concluído<"),
    (">Completed<", ">Concluído<"),
    (">Failed<", ">Falhou<"),
    (">Cancelled<", ">Cancelado<"),
    (">Paused<", ">Pausado<"),
    (">Running<", ">Executando<"),
    (">Stopped<", ">Parado<"),
    (">Idle<", ">Ocioso<"),
    (">Ready<", ">Pronto<"),
    (">Busy<", ">Ocupado<"),
    (">Waiting<", ">Aguardando<"),
    (">Queued<", ">Na fila<"),
    (">Streaming<", ">Transmitindo<"),
    (">Generating<", ">Gerando<"),
    (">Thinking<", ">Pensando<"),
    (">Processing<", ">Processando<"),
    (">Analyzing<", ">Analisando<"),
    (">Searching<", ">Buscando<"),
    (">Indexing<", ">Indexando<"),
    (">Embedding<", ">Incorporando<"),
    (">Translating<", ">Traduzindo<"),
    (">Summarizing<", ">Resumindo<"),
    (">Reviewing<", ">Revisando<"),
    (">Planning<", ">Planejando<"),
    (">Executing<", ">Executando<"),
    (">Finishing<", ">Finalizando<"),
    (">Cleaning up<", ">Limpando<"),
    (">Initializing<", ">Inicializando<"),
    (">Connecting<", ">Conectando<"),
    (">Reconnecting<", ">Reconectando<"),
    (">Authenticating<", ">Autenticando<"),
    (">Authorizing<", ">Autorizando<"),
    (">Validating<", ">Validando<"),
    (">Verifying<", ">Verificando<"),
    (">Checking<", ">Verificando<"),
    (">Testing<", ">Testando<"),
    (">Scanning<", ">Escaneando<"),
    (">Syncing<", ">Sincronizando<"),
    (">Synced<", ">Sincronizado<"),
    (">Uploading<", ">Enviando<"),
    (">Downloading<", ">Baixando<"),
    (">Installing<", ">Instalando<"),
    (">Updating<", ">Atualizando<"),
    (">Restarting<", ">Reiniciando<"),
    (">Refreshing<", ">Atualizando<"),
]

def translate_file(path):
    with open(path, "r", encoding="utf-8") as f:
        content = f.read()
    original = content
    for eng, pt in TRANSLATIONS:
        content = content.replace(eng, pt)
    if content != original:
        with open(path, "w", encoding="utf-8") as f:
            f.write(content)
        return True
    return False

changed = 0
for dirpath, dirnames, filenames in os.walk(ROOT):
    dirnames[:] = [d for d in dirnames if d != "node_modules"]
    for fname in filenames:
        if fname.endswith(".tsx") or fname.endswith(".ts"):
            path = os.path.join(dirpath, fname)
            if translate_file(path):
                changed += 1
                print(f"  translated: {path[len(ROOT)+1:]}")

print(f"\nDone. {changed} files modified.")
