#!/usr/bin/env python3
"""Third pass: remaining English strings in titles, placeholders, aria-labels."""
import os

ROOT = "/workspaces/Marinara-Engine/packages/client/src"

T = [
    # titles
    ('title="Active Context"', 'title="Contexto Ativo"'),
    ('title="Active Quests"', 'title="Missões Ativas"'),
    ('title="Add character"', 'title="Adicionar personagem"'),
    ('title="Add custom stat"', 'title="Adicionar atributo personalizado"'),
    ('title="Add item"', 'title="Adicionar item"'),
    ('title="Add objective"', 'title="Adicionar objetivo"'),
    ('title="Add quest"', 'title="Adicionar missão"'),
    ('title="Agents & Actions"', 'title="Agentes & Ações"'),
    ('title="Any extra details for the GM?"', 'title="Algum detalhe extra para o Mestre?"'),
    ('title="Apply a chat-settings preset to this chat"', 'title="Aplicar predefinição de configurações a esta conversa"'),
    ('title="Apply a saved chat-settings preset and pick a persona + characters in one step"', 'title="Aplicar predefinição salva e escolher persona + personagens em um passo"'),
    ('title="Attach file"', 'title="Anexar arquivo"'),
    ('title="Attach files"', 'title="Anexar arquivos"'),
    ('title="Attempt an in-fiction interruption — outcomes can fail"', 'title="Tentar uma interrupção na ficção — pode falhar"'),
    ('title="Attempt to Interrupt?"', 'title="Tentar Interromper?"'),
    ('title="Author\'s Notes"', 'title="Notas do Autor"'),
    ('title="Automated summary"', 'title="Resumo automático"'),
    ('title="Back to agents"', 'title="Voltar para agentes"'),
    ('title="Back to regex scripts"', 'title="Voltar para scripts regex"'),
    ('title="Back to tools"', 'title="Voltar para ferramentas"'),
    ('title="Backend default"', 'title="Padrão do backend"'),
    ('title="Basic character info — name, creator, version, tags."', 'title="Informações básicas do personagem — nome, criador, versão, tags."'),
    ('title="Branch from here"', 'title="Ramificar daqui"'),
    ('title="Brief description of this lorebook..."', 'title="Breve descrição deste livro de lore..."'),
    ('title="Brief summary of what this entry is about (used by Knowledge Router agent)."', 'title="Resumo breve desta entrada (usado pelo agente Roteador de Conhecimento)."'),
    ('title="Browse for folder"', 'title="Procurar pasta"'),
    ('title="Cancel (Esc)"', 'title="Cancelar (Esc)"'),
    ('title="Cancel edit"', 'title="Cancelar edição"'),
    ('title="Change avatar"', 'title="Alterar avatar"'),
    ('title="Character Colors"', 'title="Cores do Personagem"'),
    ('title="Character Gallery"', 'title="Galeria do Personagem"'),
    ('title="Character Lorebook"', 'title="Livro de Lore do Personagem"'),
    ('title="Character Sprites"', 'title="Sprites do Personagem"'),
    ('title="Character name"', 'title="Nome do personagem"'),
    ('title="Chat Summary"', 'title="Resumo da Conversa"'),
    ('title="Chat list"', 'title="Lista de conversas"'),
    ('title="Chat navigation"', 'title="Navegação de conversas"'),
    ('title="Choose which saved sprites to export"', 'title="Escolher quais sprites salvas exportar"'),
    ('title="Clear all memories"', 'title="Limpar todas as memórias"'),
    ('title="Clear all notes"', 'title="Limpar todas as notas"'),
    ('title="Clear debug log"', 'title="Limpar log de depuração"'),
    ('title="Clear destination"', 'title="Limpar destino"'),
    ('title="Clear messages"', 'title="Limpar mensagens"'),
    ('title="Clear queued roll"', 'title="Limpar rolagem na fila"'),
    ('title="Clear selection"', 'title="Limpar seleção"'),
    ('title="Clone from here"', 'title="Clonar daqui"'),
    ('title="Close assets"', 'title="Fechar recursos"'),
    ('title="Close character sheet"', 'title="Fechar ficha do personagem"'),
    ('title="Close chat files drawer"', 'title="Fechar gaveta de arquivos"'),
    ('title="Close choices"', 'title="Fechar escolhas"'),
    ('title="Close drawer"', 'title="Fechar gaveta"'),
    ('title="Close gallery drawer"', 'title="Fechar galeria"'),
    ('title="Close image"', 'title="Fechar imagem"'),
    ('title="Close library"', 'title="Fechar biblioteca"'),
    ('title="Close player"', 'title="Fechar player"'),
    ('title="Close quick-time event"', 'title="Fechar evento rápido"'),
    ('title="Close summary"', 'title="Fechar resumo"'),
    ('title="Close thoughts"', 'title="Fechar pensamentos"'),
    ('title="Close tracker panel"', 'title="Fechar painel de rastreamento"'),
    ('title="Close trackers"', 'title="Fechar rastreadores"'),
    ('title="Collapse panel"', 'title="Recolher painel"'),
    ('title="Collapse widget"', 'title="Recolher widget"'),
    ('title="Compare with current card"', 'title="Comparar com ficha atual"'),
    ('title="Configure Preset Variables"', 'title="Configurar Variáveis da Predefinição"'),
    ('title="Connection name"', 'title="Nome da conexão"'),
    ('title="Conversation name"', 'title="Nome da conversa"'),
    ('title="Copy as /guided command"', 'title="Copiar como comando /guided"'),
    ('title="Create Character"', 'title="Criar Personagem"'),
    ('title="Create Connection"', 'title="Criar Conexão"'),
    ('title="Create Lorebook"', 'title="Criar Livro de Lore"'),
    ('title="Create Persona"', 'title="Criar Persona"'),
    ('title="Create Preset"', 'title="Criar Predefinição"'),
    ('title="Create a new folder to group entries"', 'title="Criar nova pasta para agrupar entradas"'),
    ('title="Create custom agent"', 'title="Criar agente personalizado"'),
    ('title="Create custom tool"', 'title="Criar ferramenta personalizada"'),
    ('title="Create group"', 'title="Criar grupo"'),
    ('title="Create regex script"', 'title="Criar script regex"'),
    ('title="Creator\'s Notes"', 'title="Notas do Criador"'),
    ('title="Previous swipe"', 'title="Deslize anterior"'),
    ('title="Quest Board"', 'title="Quadro de Missões"'),
    ('title="Quest name"', 'title="Nome da missão"'),
    ('title="Quick Connection Switcher"', 'title="Troca Rápida de Conexão"'),
    ('title="Quick Switcher"', 'title="Troca Rápida"'),
    ('title="Quick replies"', 'title="Respostas rápidas"'),
    ('title="Quick replies actions to include"', 'title="Ações de respostas rápidas a incluir"'),
    ('title="Re-roll CYOA choices using the latest chat context"', 'title="Rolar novamente as escolhas CYOA com o contexto atual"'),
    ('title="Re-run character tracker only"', 'title="Reexecutar apenas rastreador de personagem"'),
    ('title="Re-run custom tracker only"', 'title="Reexecutar apenas rastreador personalizado"'),
    ('title="Re-run persona tracker (stats + inventory)"', 'title="Reexecutar rastreador de persona (atributos + inventário)"'),
    ('title="Re-run quest tracker only"', 'title="Reexecutar apenas rastreador de missões"'),
    ('title="Re-run world state tracker only"', 'title="Reexecutar apenas rastreador de estado do mundo"'),
    ('title="Reach farther into matching debris"', 'title="Alcançar mais longe nos detritos correspondentes"'),
    ('title="Rebuild memories from current chat messages"', 'title="Reconstruir memórias das mensagens atuais"'),
    ('title="Refresh voices from provider"', 'title="Atualizar vozes do provedor"'),
    ('title="Regenerate this sheet from character and current game context"', 'title="Regenerar esta ficha do personagem e contexto atual do jogo"'),
    ('title="Regex Scripts"', 'title="Scripts Regex"'),
    ('title="Remove avatar"', 'title="Remover avatar"'),
    ('title="Remove extension"', 'title="Remover extensão"'),
    ('title="Remove field"', 'title="Remover campo"'),
    ('title="Remove item"', 'title="Remover item"'),
    ('title="Remove objective"', 'title="Remover objetivo"'),
    ('title="Remove quest"', 'title="Remover missão"'),
    ('title="Remove stat"', 'title="Remover atributo"'),
    ('title="Remove theme"', 'title="Remover tema"'),
    ('title="Remove this NPC from the journal"', 'title="Remover este NPC do diário"'),
    ('title="Replay tutorial"', 'title="Repetir tutorial"'),
    ('title="Reset portrait view"', 'title="Redefinir visualização do retrato"'),
    ('title="Reset to centered max-square crop"', 'title="Redefinir para corte quadrado centralizado"'),
    ('title="Reset to default"', 'title="Redefinir para padrão"'),
    ('title="Reset to default prompt"', 'title="Redefinir para prompt padrão"'),
    ('title="Reset tracker card order"', 'title="Redefinir ordem dos cartões de rastreamento"'),
    ('title="Reset wand controls to their defaults"', 'title="Redefinir controles da varinha para padrão"'),
    ('title="Resize left sidebar"', 'title="Redimensionar barra lateral esquerda"'),
    ('title="Resize right sidebar"', 'title="Redimensionar barra lateral direita"'),
    ('title="Restart combat voice-over"', 'title="Reiniciar narração de combate"'),
    ('title="Restore this version"', 'title="Restaurar esta versão"'),
    ('title="Resume narration — your interrupt has not been committed."', 'title="Retomar narração — sua interrupção não foi confirmada."'),
    ('title="Return to conversation"', 'title="Voltar para a conversa"'),
    ('title="Return to present"', 'title="Voltar ao presente"'),
    ('title="Revert to previous save"', 'title="Reverter para o save anterior"'),
    ('title="Review Character Card Updates"', 'title="Revisar Atualizações da Ficha do Personagem"'),
    ('title="Save (Cmd+Enter)"', 'title="Salvar (Cmd+Enter)"'),
    ('title="Save current chat settings as a new preset"', 'title="Salvar configurações atuais como nova predefinição"'),
    ('title="Save edit"', 'title="Salvar edição"'),
    ('title="Save label (optional)"', 'title="Rótulo do save (opcional)"'),
    ('title="Say to party…"', 'title="Dizer ao grupo…"'),
    ('title="Scene Instructions"', 'title="Instruções de Cena"'),
    ('title="Search characters..."', 'title="Buscar personagens..."'),
    ('title="Search conversation chats…"', 'title="Buscar conversas…"'),
    ('title="Search emojis..."', 'title="Buscar emojis..."'),
    ('title="Search for GIFs"', 'title="Buscar GIFs"'),
    ('title="Search imported..."', 'title="Buscar importados..."'),
    ('title="Search in folder"', 'title="Buscar na pasta"'),
    ('title="Search in folder..."', 'title="Buscar na pasta..."'),
    ('title="Search lorebooks"', 'title="Buscar livros de lore"'),
    ('title="Search lorebooks…"', 'title="Buscar livros de lore…"'),
    ('title="Search models…"', 'title="Buscar modelos…"'),
    ('title="Search personas"', 'title="Buscar personas"'),
    ('title="Search personas or titles…"', 'title="Buscar personas ou títulos…"'),
    ('title="Search personas..."', 'title="Buscar personas..."'),
    ('title="Search presets…"', 'title="Buscar predefinições…"'),
    ('title="Search roleplay or game chats…"', 'title="Buscar conversas de roleplay ou jogo…"'),
    ('title="Search tags..."', 'title="Buscar tags..."'),
    ('title="Section name"', 'title="Nome da seção"'),
    ('title="Select a folder of PNGs"', 'title="Selecionar pasta de PNGs"'),
    ('title="Select a folder of PNGs — each filename becomes the expression name"', 'title="Selecionar pasta de PNGs — cada nome de arquivo vira o nome da expressão"'),
    ('title="Select a group…"', 'title="Selecionar um grupo…"'),
    ('title="Select all messages above"', 'title="Selecionar todas as mensagens acima"'),
    ('title="Select all messages below"', 'title="Selecionar todas as mensagens abaixo"'),
    ('title="Select assets for this game"', 'title="Selecionar recursos para este jogo"'),
    ('title="Select entries to copy or move"', 'title="Selecionar entradas para copiar ou mover"'),
    ('title="Send game turn"', 'title="Enviar turno do jogo"'),
    ('title="Set date"', 'title="Definir data"'),
    ('title="Set location"', 'title="Definir localização"'),
    ('title="Set temp"', 'title="Definir temperatura"'),
    ('title="Set time"', 'title="Definir hora"'),
    ('title="Set weather"', 'title="Definir clima"'),
    ('title="Settings and tools panel"', 'title="Painel de configurações e ferramentas"'),
    ('title="Sheet Details"', 'title="Detalhes da Ficha"'),
    ('title="Show Tracker Panel"', 'title="Mostrar Painel de Rastreamento"'),
    ('title="Show expressions"', 'title="Mostrar expressões"'),
    ('title="Show help"', 'title="Mostrar ajuda"'),
    ('title="Sort order"', 'title="Ordem de classificação"'),
    ('title="Spotify setup"', 'title="Configuração do Spotify"'),
    ('title="Start new chat"', 'title="Iniciar nova conversa"'),
    ('title="Status not tracked"', 'title="Status não rastreado"'),
    ('title="Stop combat voice-over"', 'title="Parar narração de combate"'),
    ('title="Stored guidance"', 'title="Orientação armazenada"'),
    ('title="Summary source settings"', 'title="Configurações de fonte do resumo"'),
    ('title="Summary title"', 'title="Título do resumo"'),
    ('title="Switch branch"', 'title="Trocar ramificação"'),
    ('title="System Prompt"', 'title="Prompt do Sistema"'),
    ('title="Toggle Prompt Only"', 'title="Apenas Prompt"'),
    ('title="Toggle stat tracking for this character. When enabled, the character\'s stats are included in the prompt and tracked by agents."', 'title="Ativar rastreamento de atributos. Quando ativado, os atributos são incluídos no prompt e rastreados por agentes."'),
    ('title="Add custom genre…"', 'title="Adicionar gênero personalizado…"'),
    ('title="Add custom tone…"', 'title="Adicionar tom personalizado…"'),
    # placeholders
    ('placeholder="Agent name..."', 'placeholder="Nome do agente..."'),
    ('placeholder="Agent name…"', 'placeholder="Nome do agente…"'),
    ('placeholder="Any extra details for the GM?"', 'placeholder="Algum detalhe extra para o Mestre?"'),
    ('placeholder="Additional description content…"', 'placeholder="Conteúdo adicional da descrição…"'),
    ('placeholder="Additional instructions for game generation..."', 'placeholder="Instruções adicionais para geração do jogo..."'),
    ('placeholder="Author\'s Notes…"', 'placeholder="Notas do Autor…"'),
    ('placeholder="Brief description of this lorebook..."', 'placeholder="Breve descrição deste livro de lore..."'),
    ('placeholder="Brief summary of what this entry is about (used by Knowledge Router agent)."', 'placeholder="Resumo breve desta entrada (usado pelo agente Roteador de Conhecimento)."'),
    ('placeholder="Character name"', 'placeholder="Nome do personagem"'),
    ('placeholder="Character name..."', 'placeholder="Nome do personagem..."'),
    ('placeholder="Character-specific instructions inserted through {{charSysInfo}} or the character prompt block…"', 'placeholder="Instruções específicas do personagem inseridas via {{charSysInfo}} ou bloco de prompt…"'),
    ('placeholder="Comment (e.g. \'Modern AU version\')"', 'placeholder="Comentário (ex: \'Versão AU Moderna\')"'),
    ('placeholder="Connection name…"', 'placeholder="Nome da conexão…"'),
    ('placeholder="Conversation name"', 'placeholder="Nome da conversa"'),
    ('placeholder="Creator\'s Notes…"', 'placeholder="Notas do Criador…"'),
    ('placeholder="Prompt content… (supports macros like {{user}}, {{char}}, etc.)"', 'placeholder="Conteúdo do prompt… (suporta macros como {{user}}, {{char}}, etc.)"'),
    ('placeholder="Prompt content… (supports {{user}}, {{char}}, {{// comment}}, {{trim}} macros)"', 'placeholder="Conteúdo do prompt… (suporta macros {{user}}, {{char}}, {{// comment}}, {{trim}})"'),
    ('placeholder="Prompt injected at a specific depth in the chat history…"', 'placeholder="Prompt injetado em uma profundidade específica no histórico…"'),
    ('placeholder="Quest name"', 'placeholder="Nome da missão"'),
    ('placeholder="Scene system prompt..."', 'placeholder="Prompt de sistema da cena..."'),
    ('placeholder="Script name…"', 'placeholder="Nome do script…"'),
    ('placeholder="Search characters..."', 'placeholder="Buscar personagens..."'),
    ('placeholder="Search conversation chats…"', 'placeholder="Buscar conversas…"'),
    ('placeholder="Search emojis..."', 'placeholder="Buscar emojis..."'),
    ('placeholder="Search for GIFs"', 'placeholder="Buscar GIFs"'),
    ('placeholder="Search imported..."', 'placeholder="Buscar importados..."'),
    ('placeholder="Search in folder"', 'placeholder="Buscar na pasta"'),
    ('placeholder="Search in folder..."', 'placeholder="Buscar na pasta..."'),
    ('placeholder="Search lorebooks"', 'placeholder="Buscar livros de lore"'),
    ('placeholder="Search lorebooks…"', 'placeholder="Buscar livros de lore…"'),
    ('placeholder="Search models…"', 'placeholder="Buscar modelos…"'),
    ('placeholder="Search personas"', 'placeholder="Buscar personas"'),
    ('placeholder="Search personas or titles…"', 'placeholder="Buscar personas ou títulos…"'),
    ('placeholder="Search personas..."', 'placeholder="Buscar personas..."'),
    ('placeholder="Search presets…"', 'placeholder="Buscar predefinições…"'),
    ('placeholder="Search roleplay or game chats…"', 'placeholder="Buscar conversas de roleplay ou jogo…"'),
    ('placeholder="Search tags..."', 'placeholder="Buscar tags..."'),
    ('placeholder="Section name"', 'placeholder="Nome da seção"'),
    ('placeholder="Select a group…"', 'placeholder="Selecionar um grupo…"'),
    ('placeholder="String to trim…"', 'placeholder="String para cortar…"'),
    ('placeholder="Summary title"', 'placeholder="Título do resumo"'),
    ('placeholder="System Prompt"', 'placeholder="Prompt do Sistema"'),
    ('placeholder="System prompt, post-history instructions, and depth prompt injection."', 'placeholder="Prompt do sistema, instruções pós-histórico e injeção de prompt por profundidade."'),
    ('placeholder="Text inserted after the chat history but before generation…"', 'placeholder="Texto inserido após o histórico mas antes da geração…"'),
    ('placeholder="The character\'s general description. This is sent in every prompt as part of the character\'s identity."', 'placeholder="Descrição geral do personagem. Enviada em todo prompt como parte da identidade do personagem."'),
    ('placeholder="The character\'s history, origin story, and formative life events."', 'placeholder="Histórico do personagem, origem e eventos formativos."'),
    ('placeholder="The content that will be injected into the prompt when this entry activates…"', 'placeholder="Conteúdo que será injetado no prompt quando esta entrada ativar…"'),
    ('placeholder="The default setting or situation where interactions take place."', 'placeholder="O cenário padrão ou situação onde as interações ocorrem."'),
    ('placeholder="Theme name..."', 'placeholder="Nome do tema..."'),
    ('placeholder="Title / comment (e.g. \'Modern AU version\')"', 'placeholder="Título / comentário (ex: \'Versão AU Moderna\')"'),
    ('placeholder="Connection name"', 'placeholder="Nome da conexão"'),
    ('placeholder="Select a connection…"', 'placeholder="Selecionar uma conexão…"'),
    ('placeholder="Add custom genre…"', 'placeholder="Adicionar gênero personalizado…"'),
    ('placeholder="Add custom tone…"', 'placeholder="Adicionar tom personalizado…"'),
    # option/select
    ('<option value="">Select a connection…</option>', '<option value="">Selecionar uma conexão…</option>'),
    ('<option value="">Select an ElevenLabs voice</option>', '<option value="">Selecionar uma voz ElevenLabs</option>'),
    # aria-labels
    ('aria-label="Dismiss notice"', 'aria-label="Dispensar aviso"'),
    ('aria-label="Chat list"', 'aria-label="Lista de conversas"'),
    ('aria-label="Chat navigation"', 'aria-label="Navegação de conversas"'),
    ('aria-label="Collapse panel"', 'aria-label="Recolher painel"'),
    ('aria-label="Collapse widget"', 'aria-label="Recolher widget"'),
    ('aria-label="Quick replies"', 'aria-label="Respostas rápidas"'),
    ('aria-label="Settings and tools panel"', 'aria-label="Painel de configurações e ferramentas"'),
    ('aria-label="Show Tracker Panel"', 'aria-label="Mostrar Painel de Rastreamento"'),
    ('aria-label="Show expressions"', 'aria-label="Mostrar expressões"'),
    ('aria-label="Show help"', 'aria-label="Mostrar ajuda"'),
    ('aria-label="Toggle Prompt Only"', 'aria-label="Apenas Prompt"'),
]

def translate_file(path):
    with open(path, "r", encoding="utf-8") as f:
        content = f.read()
    original = content
    for eng, pt in T:
        content = content.replace(eng, pt)
    if content != original:
        with open(path, "w", encoding="utf-8") as f:
            f.write(content)
        return True
    return False

changed = 0
for dirpath, dirnames, filenames in os.walk(ROOT):
    dirnames[:] = [d for d in dirnames if d != "node_modules"]
    for fname in filenames:
        if fname.endswith(".tsx") or fname.endswith(".ts"):
            path = os.path.join(dirpath, fname)
            if translate_file(path):
                changed += 1
                print(f"  {path[len(ROOT)+1:]}")

print(f"\nDone. {changed} files modified.")
